#!/usr/bin/env python
import sys,argparse
import pandas as pd
import numpy as np

def tab2xlsx(args):
    df = pd.read_csv(args.tab, '\t')
    writer = pd.ExcelWriter(args.xlsx)
    df.to_excel(writer, "Sheet1", index=False)
    writer.save()

def main():
    parser = argparse.ArgumentParser("tab2xlsx")
    parser.add_argument("tab", type=argparse.FileType("r"),
                        help=("file with tab-separated value"))
    parser.add_argument("xlsx", type=argparse.FileType("w"),
                       help=("excel file(.xlsx)"))
    args = parser.parse_args()
    tab2xlsx(args)

if __name__ == '__main__':
        main()
